version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  target-branch: dev
  commit-message:
    prefix: "[Dependabot]"
  labels:
      - Dependencies
  assignees:
    - Paebbels
  reviewers:
    - Paebbels
  schedule:
    interval: daily
