python-targets:
- 3
test-warnings: no
strictness: medium
max-line-length: 180
pylint:
  disable:
  - too-many-arguments
pep8:
  disable:
  - E704
  options:
    max-line-length: 180
mccabe:
  options:
    max-complexity: 20
ignore-paths:
- docs
- vhdl
