language: python

install:
  - pip3 install -U -r requirements.txt

# if: tag IS present

script:
  - cd tests/unit; python -m unittest Entity.SimpleEntities
#  - python3 ./test/Application.py

deploy:
  provider: pypi
  user: "__token__"
  password: $PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true
