language: python

install:
  - pip3 install -U -r tests/requirements.txt

# if: tag IS present

before_script:
  - export CODACY_PROJECT_TOKEN=$CODACY_TOKEN

script:
  - echo $TRAVIS_BRANCH $TRAVIS_COMMIT
  - coverage run --append -m unittest tests.unit.Tokens
  - coverage run --append -m unittest tests.unit.Entity
  - coverage run --append -m unittest tests.unit.Architecture
  - coverage report
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - codecov
  - python -m unittest tests.unit.Entity

deploy:
  provider: pypi
  user: "__token__"
  password: $PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true
