.. # This file provides the following shields: travis-ci appveyor tag release
   # license mailing gitter issues-new issues-open issues-closed issues-pr
   # issues-pr-closed github gh-logo

.. # Use http://b64.io/ to encode any image to base64. Then replace `/` with
   # `%2F` and `+` with `%2B` (or use http://meyerweb.com/eric/tools/dencoder/).
   # Beware that `?logo=data:image/png;base64,` must also be converted to
   # percent encoding so that the URL is properly parsed.

.. |SHIELD:svg:pyVHDLParser-github| image:: https://img.shields.io/badge/Paebbels-pyVHDLParser-323131?logo=github&longCache=true
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://github.com/Paebbels/pyVHDLParser
.. |SHIELD:png:pyVHDLParser-github| image:: https://raster.shields.io/badge/Paebbels-pyVHDLParser-323131?logo=github&longCache=true
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://github.com/Paebbels/pyVHDLParser

.. |SHIELD:svg:pyVHDLParser-license| image:: https://img.shields.io/badge/Apache%20License,%202.0-bd0000?longCache=true&label=license&logo=Apache&logoColor=D22128
   :alt: License
   :height: 22
.. |SHIELD:png:pyVHDLParser-license| image:: https://raster.shields.io/badge/Apache%20License,%202.0-bd0000?longCache=true&label=license&logo=Apache&logoColor=D22128
   :alt: License
   :height: 22

.. |SHIELD:svg:pyVHDLParser-tag| image:: https://img.shields.io/github/v/tag/Paebbels/pyVHDLParser?logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://github.com/Paebbels/pyVHDLParser/tags
.. |SHIELD:png:pyVHDLParser-tag| image:: https://raster.shields.io/github/v/tag/Paebbels/pyVHDLParser?logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://github.com/Paebbels/pyVHDLParser/tags

.. |SHIELD:svg:pyVHDLParser-release| image:: https://img.shields.io/github/v/release/Paebbels/pyVHDLParser?logo=GitHub&include_prereleases
   :alt: GitHub release (latest SemVer incl. including pre-releases
   :height: 22
   :target: https://github.com/Paebbels/pyVHDLParser/releases/latest
.. |SHIELD:png:pyVHDLParser-release| image:: https://raster.shields.io/github/v/release/Paebbels/pyVHDLParser?logo=GitHub&include_prereleases
   :alt: GitHub release (latest SemVer incl. including pre-releases
   :height: 22
   :target: https://github.com/Paebbels/pyVHDLParser/releases/latest

.. |SHIELD:svg:pyVHDLParser-date| image:: https://img.shields.io/github/release-date/Paebbels/pyVHDLParser?logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://github.com/Paebbels/pyVHDLParser/releases
.. |SHIELD:png:pyVHDLParser-date| image:: https://raster.shields.io/github/release-date/Paebbels/pyVHDLParser?logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://github.com/Paebbels/pyVHDLParser/releases

.. |SHIELD:svg:pyVHDLParser-lib-status| image:: https://img.shields.io/librariesio/release/pypi/pyVHDLParser
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/Paebbels/pyVHDLParser
.. |SHIELD:png:pyVHDLParser-lib-status| image:: https://raster.shields.io/librariesio/release/pypi/pyVHDLParser
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/Paebbels/pyVHDLParser

.. |SHIELD:svg:pyVHDLParser-req-status| image:: https://img.shields.io/requires/github/Paebbels/pyVHDLParser
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/Paebbels/pyVHDLParser/requirements/?branch=master
.. |SHIELD:png:pyVHDLParser-req-status| image:: https://raster.shields.io/requires/github/Paebbels/pyVHDLParser
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/Paebbels/pyVHDLParser/requirements/?branch=master

.. |SHIELD:svg:pyVHDLParser-travis| image:: https://img.shields.io/travis/com/Paebbels/pyVHDLParser?logo=Travis
   :alt: Travis - Build on 'master'
   :height: 22
   :target: https://travis-ci.com/Paebbels/pyVHDLParser
.. |SHIELD:png:pyVHDLParser-travis| image:: https://raster.shields.io/travis/com/Paebbels/pyVHDLParser?logo=Travis
   :alt: Travis - Build on 'master'
   :height: 22
   :target: https://travis-ci.com/Paebbels/pyVHDLParser

.. |SHIELD:svg:pyVHDLParser-pypi-tag| image:: https://img.shields.io/pypi/v/pyVHDLParser?logo=PyPI
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyVHDLParser/
.. |SHIELD:png:pyVHDLParser-pypi-tag| image:: https://raster.shields.io/pypi/v/pyVHDLParser?logo=PyPI
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyVHDLParser/

.. |SHIELD:svg:pyVHDLParser-pypi-status| image:: https://img.shields.io/pypi/status/pyVHDLParser?logo=PyPI
   :alt: PyPI - Status
   :height: 22
.. |SHIELD:png:pyVHDLParser-pypi-status| image:: https://raster.shields.io/pypi/status/pyVHDLParser?logo=PyPI
   :alt: PyPI - Status
   :height: 22

.. |SHIELD:svg:pyVHDLParser-pypi-python| image:: https://img.shields.io/pypi/pyversions/pyVHDLParser?logo=PyPI
   :alt: PyPI - Python Version
   :height: 22
.. |SHIELD:png:pyVHDLParser-pypi-python| image:: https://raster.shields.io/pypi/pyversions/pyVHDLParser?logo=PyPI
   :alt: PyPI - Python Version
   :height: 22

.. |SHIELD:svg:pyVHDLParser-lib-dep| image:: https://img.shields.io/librariesio/dependent-repos/pypi/pyVHDLParser
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://github.com/Paebbels/pyVHDLParser/network/dependents
.. |SHIELD:png:pyVHDLParser-lib-dep| image:: https://raster.shields.io/librariesio/dependent-repos/pypi/pyVHDLParser
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://github.com/Paebbels/pyVHDLParser/network/dependents

.. |SHIELD:svg:pyVHDLParser-codacy-quality| image:: https://img.shields.io/codacy/grade/1155f244b6f54a3a95abdaa80d6771f8?logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/manual/Paebbels/pyVHDLParser
.. |SHIELD:png:pyVHDLParser-codacy-quality| image:: https://raster.shields.io/codacy/grade/1155f244b6f54a3a95abdaa80d6771f8?logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/manual/Paebbels/pyVHDLParser

.. |SHIELD:svg:pyVHDLParser-codacy-coverage| image:: https://img.shields.io/codacy/coverage/1155f244b6f54a3a95abdaa80d6771f8?logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/manual/Paebbels/pyVHDLParser
.. |SHIELD:png:pyVHDLParser-codacy-coverage| image:: https://raster.shields.io/codacy/coverage/1155f244b6f54a3a95abdaa80d6771f8?logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/manual/Paebbels/pyVHDLParser

.. |SHIELD:svg:pyVHDLParser-codecov-coverage| image:: https://img.shields.io/codecov/c/github/Paebbels/pyVHDLParser
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/Paebbels/pyVHDLParser
.. |SHIELD:png:pyVHDLParser-codecov-coverage| image:: https://raster.shields.io/codecov/c/github/Paebbels/pyVHDLParser
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/Paebbels/pyVHDLParser

.. |SHIELD:svg:pyVHDLParser-lib-rank| image:: https://img.shields.io/librariesio/sourcerank/pypi/pyVHDLParser
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/Paebbels/pyVHDLParser/sourcerank
.. |SHIELD:png:pyVHDLParser-lib-rank| image:: https://raster.shields.io/librariesio/sourcerank/pypi/pyVHDLParser
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/Paebbels/pyVHDLParser/sourcerank

.. |SHIELD:svg:pyVHDLParser-rtd| image:: https://img.shields.io/readthedocs/pyVHDLParser
   :alt: Read the Docs
   :height: 22
   :target: https://pyVHDLParser.readthedocs.io/en/latest/
.. |SHIELD:png:pyVHDLParser-rtd| image:: https://raster.shields.io/readthedocs/pyVHDLParser
   :alt: Read the Docs
   :height: 22
   :target: https://pyVHDLParser.readthedocs.io/en/latest/
