
class VHDLLexer:
	OP_ABS = None
	# KW_ACROSS = None
	KW_ACCESS = None
	KW_AFTER = None
	KW_ALIAS = None
	KW_ALL = None
	OP_AND = None
	KW_ARCHITECTURE = None
	KW_ARRAY = None
	KW_ASSERT = None
	KW_ATTRIBUTE = None
	# KW_PSL_ASSUME = None
	# KW_AMS_ACROSS = None
	KW_BEGIN = None
	KW_BLOCK = None
	KW_BODY = None
	KW_BUFFER = None
	KW_BUS = None
	# KW_BREAK = None
	KW_CASE = None
	KW_COMPONENT = None
	KW_CONFIGURATION = None
	KW_CONSTANT = None
	KW_CONTEXT = None
	# KW_PSL_COVER = None
	KW_DEFAULT = None
	KW_DISCONNECT = None
	KW_DOWNTO = None
	KW_ELSE = None
	KW_ELSIF = None
	KW_END = None
	KW_ENTITY = None
	KW_EXIT = None
	KW_FILE = None
	KW_FOR = None
	KW_FORCE = None
	KW_FUNCTION = None
	KW_GENERATE = None
	KW_GENERIC = None
	# KW_GROUP = None
	KW_GUARDED = None
	KW_IF = None
	KW_IMPURE = None
	KW_IN = None
	KW_INERTIAL = None
	KW_INOUT = None
	KW_IS = None
	KW_LABEL = None
	KW_LIBRARY = None
	KW_LINKAGE = None
	KW_LOOP = None
	KW_PSL_LITERAL = None
	# KW_LIMIT = None
	KW_MAP = None
	OP_MOD = None
	OP_NAND = None
	KW_NEW = None
	KW_NEXT = None
	OP_NOR = None
	OP_NOT = None
	KW_NULL = None
	# KW_NATURE = None
	# KW_NOISE = None
	KW_OF = None
	KW_ON = None
	KW_OPEN = None
	OP_OR = None
	KW_OTHERS = None
	KW_OUT = None
	KW_PACKAGE = None
	KW_PARAMETER = None
	KW_PORT = None
	KW_POSTPONED = None
	KW_PRIVATE = None
	KW_PROCEDURE = None
	KW_PROCESS = None
	KW_PROTECTED = None
	KW_PURE = None
	# KW_PROCEDURAL = None
	# VHDLLexer.KW_QUANTITY: 'quantityKeyword,
	KW_RANGE = None
	KW_RECORD = None
	KW_REGISTER = None
	KW_REJECT = None
	KW_RELEASE = None
	OP_REM = None
	KW_REPORT = None
	KW_RETURN = None
	OP_ROL = None
	OP_ROR = None
	# KW_PSL_RESTRICT = None
	# KW_REFERENCE = None
	KW_SELECT = None
	KW_SEVERITY = None
	KW_SHARED = None
	KW_SIGNAL = None
	OP_SLA = None
	OP_SLL = None
	OP_SRA = None
	OP_SRL = None
	KW_SUBTYPE = None
	# KW_PSL_STRONG = None
	# KW_PSL_SEQUENCE = None
	# KW_SPECTRUM = None
	# KW_SUBNATURE = None
	KW_THEN = None
	KW_TO = None
	KW_TRANSPORT = None
	KW_TYPE = None
	# KW_TERMINAL = None
	# KW_THROUGH = None
	# KW_TOLERANCE = None
	KW_UNAFFECTED = None
	KW_UNITS = None
	KW_UNTIL = None
	KW_USE = None
	KW_VARIABLE = None
	KW_VIEW = None
	# KW_PSL_VMODE = None
	# KW_PSL_VPKG = None
	# KW_PSL_VPROP = None,
	# KW_PSL_VUNIT = None
	KW_WAIT = None
	KW_WITH = None
	KW_WHEN = None
	KW_WHILE = None
	OP_XNOR = None
	OP_XOR = None
