name: Release

on:
  repository_dispatch:
    types: [ doRelease ]

jobs:
  Release:
    name: Package and Publish to PyPI
    runs-on: ubuntu-latest
    env:
      PYTHON: ${{ github.event.client_payload.PYTHON }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Setup Python ${{ env.PYTHON }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON }}

      - name: Install dependencies for packaging and release
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine

      - name: Build Python package (source distribution)
        run: |
          python setup.py sdist

      - name: Build Python package (binary distribution - wheel)
        run: |
          python setup.py bdist_wheel

      - name: Release Python package to PyPI
#        if: startsWith(github.ref, 'refs/tags')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload dist/*
